config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  devise_for :admins

  devise_for :users,
             controllers:
                 {
                     sessions: 'users/sessions',
                     confirmations: 'users/confirmations',
                     registrations: 'users/registrations',
                     passwords: 'users/passwords',
                     unlocks: 'users/unlocks',
                     omniauth_callbacks: 'omniauth_callbacks'
                 }

  scope module: :v1, constraints: ApiVersion.new('v1', true) do
    resources :locations
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  mount Commontator::Engine => '/commontator'

  namespace :users do
    root 'profile#index'
    get 'profile/:id' => 'profile#edit', :as => :user_edit
    patch 'profile/update' => 'profile#update', :as => :user_update
    patch '/blog'=> 'blog#create'

    get '/create_product' => 'profile#new_product', :as => :create_product
    get '/edit_product/:id' => 'profile#edit_product', :as => :edit_product
    get '/product/:id' => 'profile#show_product', :as => :show_product
    post '/save_product' => 'profile#create_product', :as => :save_product
    patch '/update_product' => 'profile#update_product', :as => :update_product
    delete 'delete_product' => 'profile#delete_product', :as => :delete_product

    resources :blog do
      post 'photos'=> 'blog#photo_upload'

      patch 'photos'=> 'blog#photo_upload'
    end

  end

  get '/messages' => redirect('/conversations')
  resources :messages do
    member do
      post :new
    end
  end
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  get 'v1/location_json' => 'locations#location_json'
  get 'v1/location_image_json/:id' => 'locations#location_image_json'
  get 'getRegion' => 'locations#getRegion', as: :get_region

  get 'private_police'=> 'base#private_police', as: :private_police
  get 'term_of_use'=> 'base#term_uses', as: :term_of_use
  get 'search'=> 'locations#index', as: :search
  get 'map'=> 'map#index', as: :map
  get 'blog'=> 'blog#index', as: :blog
  get 'contacts'=> 'locations#contacts', as: :contacts
  get 'add_location'=> 'locations#new', as: :add_location
  resources :events
  get 'get_events' => 'events#get_events'
  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'

  get  'users-list' => 'users#index', :as => :users_list
  get 'company-list' => 'users#company_index', :as => :company_list

  get 'users-list/:id' => 'users#show', :as => :user_profile

  get 'blog/:id'=> 'blog#show', as: :article
  get 'about' => 'main#about', as: :about
  get 'recommendations' => 'main#recommendations', as: :recommendations

  post 'photos'=> 'locations#photo_upload'
  patch 'locations'=> 'locations#create'
  patch 'photos'=> 'locations#photo_upload'

  get 'update_regions' => 'base#update_regions', as: 'update_regions'

  get 'sitemap.xml' => 'main#sitemap', format: :xml, as: :sitemap
  get 'robots.txt' => 'main#robots', format: :text, as: :robots

  resources :locations do

    resources :blog
  end

  resources :regions do
    resources :locations do
      resources :blog
    end
  end

  resources :competitions

end

app/controllers/conversations_controller.rb
class ConversationsController < BaseController
  before_filter :authenticate_user!
  helper_method :mailbox, :conversation

  before_action :mailbox

  def create
    recipient_emails = conversation_params(:recipients).split(',')
    recipients = User.where(email: recipient_emails).all

    conversation = current_user.send_message(recipients, *conversation_params(:body, :subject)).conversation
  end

  def index
    @conversations ||= @mailbox.inbox.page(params[:page]).per_page(25)
    @conversationscount ||= current_user.mailbox.inbox.all
    @trash ||= current_user.mailbox.trash.all
  end


  def reply
    current_user.reply_to_conversation(conversation, params[:body])
    redirect_to conversation_path(@conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  def show
    @conversation ||= @mailbox.conversations.find(params[:id])
    conversation.mark_as_read(current_user)
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :back
  end

  def trashbin
    @conversations ||= @mailbox.inbox.page(params[:page]).per_page(25)
    @conversationscount ||= current_user.mailbox.inbox.all
    @trash ||=  current_user.mailbox.trash.page(params[:page]).per_page(25)
    @trashcount ||= @mailbox.trash.all
  end

  def empty_trash
    current_user.mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(:deleted => true)
    end
    redirect_to :conversations
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end
end

app/helpers/users/conversations_helper.rb
module Users::ConversationsHelper
end

app/views/conversations/index.html.erb
<div class="row">

  <div class="col-xs-12" >
    <div class="page-header">
      <h3>Личные сообщения <small><a href="<%= conversations_path %>"> Входящие (<%= @conversationscount.count %>) </a> |
        <a href="<%= trashbin_conversations_path %>"> Корзина (<%= @trash.count %>)</a></small></h3>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <table class="table table-hover table-striped">
      <tr>
        <th>Отправитель</th>
        <th>Тема</th>
        <th>Дата</th>
        <th></th>
      </tr>
      <% if @conversations == nil || @conversations.empty? %>
          <i>У вас нет личных сообщений</i>
      <% end %>
      <% @conversations.each do |conversation| %>
          <tr class="<% if !conversation.is_read?(current_user) %>success<% end %>">
            <td >
              <% conversation.participants.each do |participant| %>
                  <% if participant != current_user %>
                      <% if conversation.is_read?(current_user) %> <%= participant.name %>
                      <% else %>
                          <b> <%= participant.name %> </b>
                      <% end %>
                  <% end %>
              <% end %>
            </td>
            <td >
              <% if conversation.is_read?(current_user) %>
                  <%= link_to conversation.subject, conversation_path(conversation) %> </td>
              <% else %>
                  <b><%= link_to conversation.subject, conversation_path(conversation) %></b> </td>
              <% end %>
              <td >
                <% if conversation.is_read?(current_user) %> <%= Russian::strftime(conversation.updated_at, '%d %B %Y')  %></td>
                <% else %>
                    <b> <%= Russian::strftime(conversation.updated_at, '%d %B %Y') %> </b>
                    </td>
                <% end %>
                <td >
                  <%= link_to '<i class="fa fa-trash fa-2x"></i>'.html_safe, {:controller => 'conversations', :action => 'trash', :id => conversation.id}, :title => 'Удалить', :method => 'post' %> &nbsp; &nbsp;
                </td>
                </tr>
      <% end %>
    </table>
    <%= will_paginate @conversations %>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="row">

  <div class="col-xs-12">
    <div class="page-header">
      <h3>Личные сообщения
        <small><%= @conversation.subject %></small>
      </h3>
    </div>
  </div>
</div>

<div class="row">

  <div class="col-xs-12">
    <div class="messages-body">
        <% @conversation.receipts_for(current_user).each do |receipt| %>
            <% message = receipt.message %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= message.sender.name %></h3>
          </div>
          <div class="panel-body">
            <%= message.body.html_safe %>
            <span class="timestamp">Отправленно</span>
                <span class="timestamp">
                    <%= time_ago_in_words(message.updated_at) %>
                </span>
            <span class="timestamp">назад.</span>
          </div>
        </div>
        <% end %>
    </div>
      <%= render 'messages/form', conversation: @conversation %>

  </div>
</div>

<script type="application/javascript">

$(document).ready(function () {
    var s = document.body.scrollHeight - 270;
    window.scrollTo(0,s);

});
</script>

app/views/conversations/trashbin.html.erb
<div class="row">

  <div class="col-xs-12" >
    <div class="page-header">
      <h3>Корзина <small><a href="<%= conversations_path %>"> Входящие (<%= @conversationscount.count %>) </a> |
        <a href="<%= trashbin_conversations_path %>"> Корзина (<%= @trash.count %>)</a>
        </small></h3>
    </div>
  </div>
</div>
<div class="row">
  <p>
    <% if @trashcount.count > 0 %><%= button_to 'Очистить корзину', 'empty_trash', :confirm => 'Очистить корзину?', :class => 'btn btn-primary btn-danger' %>
    <% end %>
  </p>
  <div class="col-xs-12">

    <table class="table table-hover table-striped">
      <tr>
        <th>Отправитель</th>
        <th>Тема</th>
        <th>Дата</th>
        <th></th>
      </tr>
      <% if @trash == nil || @trash.empty? %>
          <i>Корзина пуста</i>
      <% end %>
      <% @trash.each do |conversation| %>
          <tr class="<% if !conversation.is_read?(current_user) %>success<% end %>">
            <td >
              <% conversation.participants.each do |participant| %>
                  <% if participant != current_user %>
                      <% if conversation.is_read?(current_user) %> <%= participant.name %>
                      <% else %>
                          <b> <%= participant.name %> </b>
                      <% end %>
                  <% end %>
              <% end %>
            </td>
            <td >
              <% if conversation.is_read?(current_user) %>
                  <%= link_to conversation.subject, conversation_path(conversation) %> </td>
              <% else %>
                  <b><%= link_to conversation.subject, conversation_path(conversation) %></b> </td>
              <% end %>
              <td >
                <% if conversation.is_read?(current_user) %> <%= Russian::strftime(conversation.updated_at, '%d %B %Y')  %></td>
                <% else %>
                    <b> <%= Russian::strftime(conversation.updated_at, '%d %B %Y') %> </b>
                    </td>
                <% end %>
                <td >
                  <%= link_to '<i class="fa fa-inbox fa-2x"></i>'.html_safe, {:controller => "conversations", :action => "untrash", :id => conversation.id}, :title => 'Восстановить', :method => 'post' %>
                </td>
                </tr>
      <% end %>
    </table>
    <%= will_paginate @trash %>
  </div>
</div>