config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  devise_for :admins

  devise_for :users,
             controllers:
                 {
                     sessions: 'users/sessions',
                     confirmations: 'users/confirmations',
                     registrations: 'users/registrations',
                     passwords: 'users/passwords',
                     unlocks: 'users/unlocks',
                     omniauth_callbacks: 'omniauth_callbacks'
                 }

  scope module: :v1, constraints: ApiVersion.new('v1', true) do
    resources :locations
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  mount Commontator::Engine => '/commontator'

  namespace :users do
    root 'profile#index'
    get 'profile/:id' => 'profile#edit', :as => :user_edit
    patch 'profile/update' => 'profile#update', :as => :user_update
    patch '/blog'=> 'blog#create'

    get '/create_product' => 'profile#new_product', :as => :create_product
    get '/edit_product/:id' => 'profile#edit_product', :as => :edit_product
    get '/product/:id' => 'profile#show_product', :as => :show_product
    post '/save_product' => 'profile#create_product', :as => :save_product
    patch '/update_product' => 'profile#update_product', :as => :update_product
    delete 'delete_product' => 'profile#delete_product', :as => :delete_product

    resources :blog do
      post 'photos'=> 'blog#photo_upload'

      patch 'photos'=> 'blog#photo_upload'
    end

  end

  get '/messages' => redirect('/conversations')
  resources :messages do
    member do
      post :new
    end
  end
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  get 'v1/location_json' => 'locations#location_json'
  get 'v1/location_image_json/:id' => 'locations#location_image_json'
  get 'getRegion' => 'locations#getRegion', as: :get_region

  get 'private_police'=> 'base#private_police', as: :private_police
  get 'term_of_use'=> 'base#term_uses', as: :term_of_use
  get 'search'=> 'locations#index', as: :search
  get 'map'=> 'map#index', as: :map
  get 'blog'=> 'blog#index', as: :blog
  get 'contacts'=> 'locations#contacts', as: :contacts
  get 'add_location'=> 'locations#new', as: :add_location
  resources :events
  get 'get_events' => 'events#get_events'
  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'

  get  'users-list' => 'users#index', :as => :users_list
  get 'company-list' => 'users#company_index', :as => :company_list

  get 'users-list/:id' => 'users#show', :as => :user_profile

  get 'blog/:id'=> 'blog#show', as: :article
  get 'about' => 'main#about', as: :about
  get 'recommendations' => 'main#recommendations', as: :recommendations

  post 'photos'=> 'locations#photo_upload'
  patch 'locations'=> 'locations#create'
  patch 'photos'=> 'locations#photo_upload'

  get 'update_regions' => 'base#update_regions', as: 'update_regions'

  get 'sitemap.xml' => 'main#sitemap', format: :xml, as: :sitemap
  get 'robots.txt' => 'main#robots', format: :text, as: :robots

  resources :locations do

    resources :blog
  end

  resources :regions do
    resources :locations do
      resources :blog
    end
  end

  resources :competitions

end

app/views/shared/_article_list_view.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4" >
    <% if article_list_view.logo.present?  %>
        <%= link_to image_tag(article_list_view.logo.url(:medium), :class => 'img-responsive'), article_url(article_list_view.id)%>
    <% end %>
  </div>
  <div class="col-xs-12 col-sm-8" >
    <div class="page-header">
      <h3><%= link_to article_list_view.title, article_url(article_list_view.id)%> <small><%= article_list_view.category.title %></small></h3>
    </div>
    <p class="blog_date">Дата создания - <%= Russian::strftime(article_list_view.created_at, '%d %B %Y') %></p>
    <p><%= truncate_html(strip_tags(article_list_view.description.html_safe) , :length => 400, :omission => '...') %></p>
    <% if article_list_view.user.present? %>
        <div class="media user_info">
          <div class="media-left">
            <a href="<%= user_profile_url(article_list_view.user.id) %>">
              <%= image_tag article_list_view.user.avatar.url(:mini), :class => 'media-object img-circle'%>
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading">
              <%= article_list_view.user.name if article_list_view.user.name.present? && article_list_view.user.name.present? %> <%= article_list_view.user.soname if article_list_view.user.soname.present? && article_list_view.user.soname.present? %>
            </h4>
          </div>
        </div>

    <% end %>
  </div>
</div>

app/views/shared/_location_list_view.html.erb
<% @locations.each do |location |%>
<div class="col-xs-12 col-sm-4 col-md-3">
  <div class="thumbnail location_block">
    <% if location.photos.present? && location.photos.where(:is_main => true).first.present? %>
        <%= link_to image_tag(location.photos.where(:is_main => true).first.image.url(:to_main)),  region_location_url(location.region.id, location.id)%>
    <% end %>
    <div class="caption">
      <h3><a href="<%= region_location_url(location.region.id, location.id) %>"><%= location.title %></a></h3>
      <!--<p><%#= location.description %></p>-->

    </div>
  </div>
</div>
<% end %>

<div class="col-xs-12">
  <%= will_paginate @locations, renderer: BootstrapPagination::Rails %>
</div>

app/views/shared/_search_form.html.erb
<div class="well">
<%= form_for_filterrific filterrific do |f| %>
      <%= f.hidden_field :is_show, :value => true %>
    <div class="form-group row">

      <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
      <div class="col-xs-12">
      <%= f.text_field(
                  :title,
                  class: 'form-control filterrific-periodically-observed', placeholder: 'Название водоема'
          ) %>
    </div>
    </div>

      <div class="row">
    <div class="form-group col-xs-12 col-md-3">
      <%= f.select(
                  :with_fish_id,
                  @filterrific.select_options[:with_fish_id],
                  { include_blank: '- Не выбранно -' },{ :multiple => true}
          ) %>
    </div>

    <div class="form-group col-xs-12 col-md-3">
      <%= f.select(
                  :with_region_id  ,
                  @filterrific.select_options[:with_region_id],
                  { include_blank: '- Не выбранно -'},{ :multiple => true }
          ) %>
    </div>

    <div class="form-group col-xs-12 col-md-3">
      <%= f.number_field(:with_distance_gte, class: 'form-control filterrific-periodically-observed', placeholder: 'Расстояние не более') %>
    </div>

    <div class="form-group col-xs-12 col-md-3">
      <div class="checkbox ">
        <label>
          <%= f.check_box (:is_payed) %> Только бесплатные
        </label>
      </div>
    </div>
    </div>
        <div class="row">
        <div class="col-xs-12 col-md-3">
          <%= link_to(
                      'Сбросить фильтр',
                      reset_filterrific_url, :class => 'btn btn-primary pull-left'
              ) %>
        </div>
      </div>


    <%# add an automated spinner to your form when the list is refreshed %>
    <%= render_filterrific_spinner %>
<% end %>

</div>

app/views/shared/_search_form_region.html.erb
<div class="well">
<%= form_for_filterrific filterrific do |f| %>
      <%= f.hidden_field :with_region_id, :value => params[:id] %>
      <%= f.hidden_field :is_show, :value => true %>
    <div class="form-group row">

      <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
      <div class="col-xs-12 col-md-6">
      <%= f.text_field(
                  :title,
                  class: 'form-control filterrific-periodically-observed', placeholder: 'Название водоема'
          ) %>
    </div>
    </div>
    <div class="form-group row">
      <div class="col-xs-12 col-md-6">
      <%= f.select(
                  :with_fish_id,
                  @filterrific.select_options[:with_fish_id],
                  { include_blank: '- Не выбранно -' },{ :multiple => true}
          ) %>
    </div>
    </div>

    <div class="form-group row">
      <div class="col-xs-12 col-md-3">
      <%= f.number_field(:with_distance_gte, class: 'form-control filterrific-periodically-observed', placeholder: 'Расстояние не более') %>
    </div>
    </div>

    <div class="form-group row">
      <div class="checkbox col-xs-12 col-md-3">
        <label>
          <%= f.check_box (:is_payed) %> Только бесплатные
        </label>
      </div>
    </div>

    <div class="form-grou rowp">
      <div class="col-xs-12 col-md-3">
      <%= link_to(
                  'Сбросить фильтр',
                  reset_filterrific_url,
          ) %>
    </div>
    </div>
    <%# add an automated spinner to your form when the list is refreshed %>
    <%= render_filterrific_spinner %>
<% end %>
</div>